#pragma once

#define VERSION "1.0"

#define SCROLLBAR_W 30
#define ITEM_W 32
#define ITEM_H 32
#define ITEM_PAD_X 0
#define ITEM_PAD_Y 0
#define MAX_ITEMS_PER_ROW 6
#define DEF_ITEMS_PER_COL 4
#define ITEMPANE_W ((ITEM_W+ITEM_PAD_X)*MAX_ITEMS_PER_ROW+ITEM_PAD_X+SCROLLBAR_W)
#define ITEMPANE_H ((ITEM_H+ITEM_PAD_Y)*DEF_ITEMS_PER_COL+ITEM_PAD_Y)
#define ITEMPANE_PAD_X 8
#define ITEMPANE_PAD_Y 8
#define INFOPANE_W ITEMPANE_W
#define TITLE_PAD_X 4
#define TITLE_PAD_Y 4
#define TITLE_W (ITEMPANE_W-TITLE_PAD_X*2)
#define TITLE_H 30
#define DESCRIPTION_W TITLE_W
#define DESCRIPTION_H 200
#define DESCRIPTION_PAD_X TITLE_PAD_X
#define DESCRIPTION_PAD_Y 4
#define INFOPANE_PAD_X ITEMPANE_PAD_X
#define INFOPANE_PAD_Y 4
#define INFOPANE_W ITEMPANE_W
#define INFOPANE_H (TITLE_H+TITLE_PAD_Y*2+DESCRIPTION_H+DESCRIPTION_PAD_Y*2)
#define PANEL_TAG_H 24
#define TAB_W (ITEMPANE_W+ITEMPANE_PAD_X*2)
#define TAB_H (ITEMPANE_H+INFOPANE_H+ITEMPANE_PAD_Y*2+INFOPANE_PAD_Y*2)
#define TAB_PAD_X 0
#define TAB_PAD_Y 0
#define PANEL_W (TAB_W+TAB_PAD_X*2)
#define PANEL_H (TAB_H+TAB_PAD_Y*2+PANEL_TAG_H)
#define PANEL_PAD_X 8
#define PANEL_PAD_Y 8
#define GAMEBUTTON_W PANEL_W
#define GAMEBUTTON_H 30
#define GAMEBUTTON_PAD_X PANEL_PAD_X
#define GAMEBUTTON_PAD_Y 8
#define WINDOW_W (PANEL_W+PANEL_PAD_X*2)
#define WINDOW_H (PANEL_H+PANEL_PAD_Y*2+GAMEBUTTON_H+GAMEBUTTON_PAD_Y*2)
#define PANE_GAP_H 8

#define PANEL_X PANEL_PAD_X
#define PANEL_Y PANEL_PAD_Y
#define TAB_X (PANEL_X+TAB_PAD_X)
#define TAB_Y (PANEL_Y+TAB_PAD_Y+PANEL_TAG_H)
#define ITEMPANE_X (TAB_X+ITEMPANE_PAD_X)
#define ITEMPANE_Y (TAB_Y+ITEMPANE_PAD_Y)
#define INFOPANE_X (TAB_X+INFOPANE_PAD_X)
#define INFOPANE_Y (ITEMPANE_Y+ITEMPANE_H+PANE_GAP_H+INFOPANE_PAD_Y)
#define TITLE_X (INFOPANE_X+TITLE_PAD_X)
#define TITLE_Y (INFOPANE_Y+TITLE_PAD_Y)
#define DESCRIPTION_X (INFOPANE_X+DESCRIPTION_PAD_X)
#define DESCRIPTION_Y (TITLE_Y+TITLE_H+TITLE_PAD_Y+DESCRIPTION_PAD_Y)
#define GAMEBUTTON_X GAMEBUTTON_PAD_X
#define GAMEBUTTON_Y (PANEL_Y+PANEL_H+PANEL_PAD_Y+GAMEBUTTON_PAD_Y)

#define ITEMBOX_X(INDEX) (ITEMPANE_X+((INDEX)%MAX_ITEMS_PER_ROW)*(ITEM_W+ITEM_PAD_X)+ITEM_PAD_X)
#define ITEMBOX_Y(INDEX) (ITEMPANE_Y+((INDEX)/MAX_ITEMS_PER_ROW)*(ITEM_H+ITEM_PAD_Y)+ITEM_PAD_Y)

#define HUDPANE_PAD_X 8
#define HUDPANE_PAD_Y 8
#define HUDPANE_W (TAB_W-HUDPANE_PAD_X*2)
#define STATE_PAD_X 8
#define STATE_PAD_Y 8
#define STATE_TEXT_W 80
#define STATE_W (HUDPANE_W-STATE_PAD_X*2-STATE_TEXT_W)
#define STATE_H 20
#define STATE_NUM 6
#define HUDPANE_H (((STATE_H+STATE_PAD_Y)*STATE_NUM)+STATE_PAD_Y)

#define HUDPANE_X (TAB_X+HUDPANE_PAD_X)
#define HUDPANE_Y (TAB_Y+HUDPANE_PAD_Y)
#define STATE_X (HUDPANE_X+STATE_PAD_X+STATE_TEXT_W)
#define STATE_Y(INDEX) (HUDPANE_Y+STATE_PAD_Y+(STATE_PAD_Y+STATE_H)*(INDEX))

//TODO: put this into cmake file
#define ENGLISH 0
#define CHINESE 1
#define LANGUAGE ENGLISH

#if   (LANGUAGE == ENGLISH)
#include "UIFltk/MenuEN.h"
#elif (LANGUAGE == CHINESE)
#include "UIFltk/MenuCH.h"
#endif
